apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-hello-world
  labels:
    app: kubernetes-hello-world
  {{ if .Values.changeCause }}
  annotations:
    kubernetes.io/change-cause: {{ .Values.changeCause }}
  {{ end }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kubernetes-hello-world
  template:
    metadata:
      labels:
        app: kubernetes-hello-world
    spec:
      containers:
        - name: hello-world
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              cpu: 10m
              memory: 32Mi
