{{- if not .Values.USE_NODEPORT -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-hello-world
  labels:
    app: kubernetes-hello-world
spec:
  rules:
    - host: {{ required "`host` value is required." .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubernetes-hello-world
                port:
                  name: http
{{- end -}}
