{{- if not .Values.USE_NODEPORT -}}
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-hello-world
  labels:
    app: kubernetes-hello-world
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: kubernetes-hello-world

{{- end -}}
